### ISSUE TITLE
Chrome inspector offline mode still sends messages

### ISSUE THREAD

**Issue by YoavHortman** [partykit/partykit#622]
Using chrome's network tab and setting network throttling to offline doesn't stop messages from being sent and does not disconnect from the socket.

**Comment by threepointone** [comment]
Just checked, looks like that's a bug with Chrome's devtools, it keeps the websocket alive and still sends messages up (but doesn't accept any incoming messages) There's an open bug here on the chromium tracker https://bugs.chromium.org/p/chromium/issues/detail?id=627188

Closing this since there's nothing we can do here, sorry!

**Comment by threepointone** [comment]
This appears to be the bug being tracked https://bugs.chromium.org/p/chromium/issues/detail?id=423246
