### ISSUE TITLE
This expression is not constructable

### ISSUE THREAD

**Issue by nichoth** [partykit/partykit#836]
Following the docs, https://docs.partykit.io/guides , we have 
```js
import PartySocket from "partysocket";

// connect to our server
const partySocket = new PartySocket({
  host: "localhost:1999",
  room: "my-room"
});
```

But, I right away get a tyepscript error,

> This expression is not constructable.
 > Type 'typeof import("/Users/nick/code/logux-party/node_modules/partysocket/index")' has no construct signatures.ts(2351)

<img width="656" alt="image" src="https://github.com/partykit/partykit/assets/5776508/243cc3ae-cb48-48af-912b-edb92e9fe292">

My code is just copy/paste of the example.

**Comment by threepointone** [comment]
This problem is usually around typescript's module resolution. Typescript will error, but the code will actually "work". The usual recommendation has been to change the value there, but I think I have a better answer. I'm going to export it as a named export from the package, so you can do `import {PartySocket} from 'partysocket'`. Just did a release, available in `partysocket@1.0.1`
